# Generated by Django 6.0.3 on 2026-04-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_delete_botapplication_application_consent_given_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('funnel_stage', models.CharField(default='started', max_length=50)),
                ('start_timestamp', models.DateTimeField(null=True)),
                ('consent_given', models.BooleanField(blank=True, null=True)),
                ('consent_timestamp', models.DateTimeField(null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('school_type', models.CharField(blank=True, max_length=50, null=True)),
                ('gpa_raw', models.CharField(blank=True, max_length=50, null=True)),
                ('gpa', models.FloatField(null=True)),
                ('languages', models.JSONField(default=list, null=True)),
                ('ielts_score', models.FloatField(blank=True, null=True)),
                ('ent_score', models.IntegerField(blank=True, null=True)),
                ('olympiads', models.JSONField(default=list, null=True)),
                ('courses', models.JSONField(default=list, null=True)),
                ('projects', models.JSONField(default=list, null=True)),
                ('essay_text', models.TextField(blank=True, null=True)),
                ('essay_word_count', models.IntegerField(null=True)),
                ('essay_nlp', models.JSONField(blank=True, null=True)),
                ('scenario_choices', models.JSONField(default=dict, null=True)),
                ('fingerprint_display', models.JSONField(null=True)),
                ('fingerprint_reliable', models.BooleanField(blank=True, null=True)),
                ('timer_violations', models.IntegerField(default=0)),
                ('uploaded_files', models.JSONField(default=list, null=True)),
                ('score_prediction', models.CharField(blank=True, max_length=20, null=True)),
                ('score_confidence', models.FloatField(null=True)),
                ('score_probabilities', models.JSONField(null=True)),
                ('score_explanation', models.JSONField(null=True)),
                ('score_radar', models.JSONField(null=True)),
                ('score_flags', models.JSONField(null=True)),
                ('scored_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Заявка (бот)',
                'verbose_name_plural': 'Заявки (бот)',
                'db_table': 'applications',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='application',
            name='consent_given',
        ),
        migrations.RemoveField(
            model_name='application',
            name='consent_timestamp',
        ),
        migrations.RemoveField(
            model_name='application',
            name='essay_text',
        ),
        migrations.RemoveField(
            model_name='application',
            name='essay_word_count',
        ),
        migrations.RemoveField(
            model_name='application',
            name='funnel_stage',
        ),
        migrations.RemoveField(
            model_name='application',
            name='score_confidence',
        ),
        migrations.RemoveField(
            model_name='application',
            name='score_explanation',
        ),
        migrations.RemoveField(
            model_name='application',
            name='score_flags',
        ),
        migrations.RemoveField(
            model_name='application',
            name='score_prediction',
        ),
        migrations.RemoveField(
            model_name='application',
            name='score_probabilities',
        ),
        migrations.RemoveField(
            model_name='application',
            name='score_radar',
        ),
        migrations.RemoveField(
            model_name='application',
            name='scored_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='start_timestamp',
        ),
        migrations.RemoveField(
            model_name='application',
            name='uploaded_files',
        ),
        migrations.AlterField(
            model_name='application',
            name='essay_nlp',
            field=models.JSONField(blank=True, null=True, verbose_name='NLP-анализ эссе'),
        ),
        migrations.AlterField(
            model_name='application',
            name='fingerprint_display',
            field=models.JSONField(blank=True, null=True, verbose_name='SLPI профиль'),
        ),
        migrations.AlterField(
            model_name='application',
            name='fingerprint_reliable',
            field=models.BooleanField(blank=True, null=True, verbose_name='Fingerprint надёжен'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='application',
            name='scenario_choices',
            field=models.JSONField(blank=True, default=dict, verbose_name='Выборы сценариев'),
        ),
    ]
