# Generated by Django 6.0.3 on 2026-04-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_application_essay_nlp_fingerprint_scenarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ent_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='ЕНТ'),
        ),
        migrations.AddField(
            model_name='application',
            name='ielts_score',
            field=models.FloatField(blank=True, null=True, verbose_name='IELTS'),
        ),
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(choices=[('bot', 'Telegram Bot'), ('web', 'Веб-форма'), ('manual', 'Вручную')], db_index=True, default='web', max_length=10, verbose_name='Источник'),
        ),
    ]
